services:
  educacion-cooperativa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educacion-cooperativa
    ports:
      - "8888:8888"
    volumes:
      - ./documentos:/app/documentos:z
    environment:
      - PYTHONUNBUFFERED=1
      - PASSWORD=admin
    restart: unless-stopped
