services:
  griego-md:
    build:
      context: ..
      dockerfile: visor_markdown/Dockerfile
    container_name: griego-markdown
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8888:8888"
    volumes:
      - ./:/app/:z
      - ../Griego2Docs/documentos:/app/documentos:z
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    working_dir: /app/visor_markdown
